# Generated by Django 2.2.7 on 2020-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createUser', models.CharField(default='', max_length=50)),
                ('todoText', models.CharField(max_length=150)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
