# Generated by Django 2.2.7 on 2020-01-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200131_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['createDate'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todo'},
        ),
    ]
